name: discord_sender
description: "automatic sending of messages to discord channels."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  fluent_ui: ^4.8.3
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0
  #make request to api
  retrofit: '>=4.0.0 <5.0.0'
  go_router: ^14.2.1
  system_theme: ^3.0.0
  window_manager: ^0.3.7
  http: ^1.2.1
  json_annotation: ^4.8.1
  file_picker: ^8.0.6
  desktop_drop: ^0.4.4
  flutter_markdown: ^0.7.3
  url_launcher: ^6.2.4
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  path: ^1.9.0
  uuid: ^4.3.3
  crypto: ^3.0.3
  win32: ^5.3.0
  device_info_plus: ^10.1.1
  flutter_linkify: ^6.0.0
  reorderables: ^0.6.0
  dio: ^5.4.3+1
  provider: ^6.1.2
  bloc: ^8.1.4
  emoji_picker_flutter: ^2.1.1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.2 
  build_runner: ^2.4.11
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter:
  uses-material-design: true


